name = "foodtracker-api-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-15"

[vars]
# Non-sensitive environment variables  
CORS_ORIGIN = "expo://localhost"

# Secrets (set via wrangler secret put)
# GEMINI_API_KEY
# USDA_API_KEY